version: '3.8'

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=development
    command: npm run dev
