version: '3.8'

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
    command: npm start
